#!/bin/bash

#PBS -N makedb
#PBS -j oe
#PBS -m abe
#PBS -M jmif9945@uni.sydney.edu.au
#PBS -P jcomvirome
#PBS -l select=1:ncpus=4:mem=40GB
#PBS -l walltime=12:00:00
#PBS -M jmif9945@uni.sydney.edu.au


# Function to run EMBOSS getorf and cluster the output using DIAMOND
function makedbDiamond() {
    # Check if the input file is provided
    if [[ -z "$input" ]]; then
        echo "Error: Please provide a full path to the input FASTA file."
        return 1
    fi

    # Define input and output files
    INPUT_FASTA="$input"
    FILE_PREFIX=$(basename "${INPUT_FASTA}" .fasta)
    CLUST_DB="${FILE_PREFIX}.dmnd"
    SCRATCH_DIR="/scratch/VELAB"

    # Ensure scratch directory exists
    mkdir -p "${SCRATCH_DIR}"
    
    # Activate the diamond_cluster conda environment
    CONDA_BASE=$(conda info --base)
    source "${CONDA_BASE}/etc/profile.d/conda.sh"
    conda activate diamond_cluster

    # Make DIAMOND database from representative sequences
    diamond makedb --in "${INPUT_FASTA}" -d "${CLUST_DB}"
}

wd="$(dirname "${input}")"             # working dir
# cd working dir
cd "$wd" || exit

# Call the clusterDiamond function with the provided input file
makedbDiamond "$input"


