#!/bin/bash
###############################################################################################################
#                                            BatchArtemisSRAMiner                                             #
#                                                JCO Mifsud                                                   #
#                                                   2023                                                      #
###############################################################################################################

# Underlying pbs script that is run using the wrapper script YOURPROJECT_blastxRVDB.sh
# This script will run blastx on eacj contigs.fa file against the RVDB database
# the RVDB is a viral database that contains DNA and RNA viruses
# it is useful for picking up non-rdrp segements / contigs and DNA viruses
# It will then extract the contigs that have a blast hit to the RVDB database which can be used in later steps such as Blastx against the NR and NT databases.

#PBS -N blastx_RVDB_array
#PBS -l select=1:ncpus=12:mem=120GB
#PBS -M jmif9945@uni.sydney.edu.au
#PBS -m abe

##load modules
module load blast
module load diamond/2.1.6

# blastx
function BlastxRVDB {
    diamond blastx -q "$inpath"/"$library_id".contigs.fa -d "$db" -t "$tempdir" -o "$outpath"/"$library_id"_RVDB_blastx_results.txt -e 1E-10 -c1 -k1 -b "$MEM" -p "$CPU" -f 6 qseqid qlen sseqid stitle pident length evalue --ultra-sensitive --iterate
}

#tool to extract contigs from trinity assembly Blast to fasta
function blastToFasta {
    grep -i ".*" "$outpath"/"$library_id"_RVDB_blastx_results.txt | cut -f1 | sort | uniq >"$outpath"/"$library_id""_temp_contig_names.txt" #by defult this will grab the contig name from every blast result line as I commonly use a custom protein database containing only viruses
    grep -A1 -I -Ff "$outpath"/"$library_id""_temp_contig_names.txt" "$inpath"/"$library_id".contigs.fa >"$outpath"/"$library_id"_RVDB_blastcontigs.fasta
    sed -i 's/--//' "$outpath"/"$library_id"_RVDB_blastcontigs.fasta                            # remove -- from the contigs
    sed -i '/^[[:space:]]*$/d' "$outpath"/"$library_id"_RVDB_blastcontigs.fasta                 # remove the white space
    sed --posix -i "/^\>/ s/$/"_$library_id"/" "$outpath"/"$library_id"_RVDB_blastcontigs.fasta # annotate the contigs
    rm "$outpath"/"$library_id""_temp_contig_names.txt"
}

# Setting variables - you shouldn't really need to change these other than resource allocations
# read in list of file names or accessions for example could be several fastq.gz files (paired or single) or just the accession id's
readarray -t myarray <"$file_of_accessions"
export library_run=${myarray["$PBS_ARRAY_INDEX"]}
library_run_without_path="$(basename -- $library_run)"
library_id=$(echo $library_run_without_path | sed 's/\.contigs.fa//g')

wd=/project/"$root_project"/"$project"/blast_results
inpath=/project/"$root_project"/"$project"/contigs/final_contigs # location of reads and filenames
outpath=/project/"$root_project"/"$project"/blast_results        # location of megahit output
tempdir=/scratch/"$root_project"/
CPU=12
MEM=2

# cd working dir
cd "$wd" || exit

BlastxRVDB
blastToFasta
