#!/bin/bash
###############################################################################################################
#                                            BatchArtemisSRAMiner                                             #   
#                                                JCO Mifsud                                                   # 
#                                                   2023                                                      # 
###############################################################################################################

# script to blastn and extract positive virus contigs

#PBS -N blastn_custom_array
#PBS -l select=1:ncpus=12:mem=120GB
#PBS -l walltime=48:00:00
#PBS -M jmif9945@uni.sydney.edu.au
#PBS -m abe

##load modules
module load blast+

nt_db_basename=$(basename "$db")

# blastn
function Blastn {
    blastn -query "$input" -db "$db" -out "$outpath"/"$library_id"_"$nt_db_basename"_nt_blastn_results.txt -max_target_seqs 10 -num_threads "$CPU" -mt_mode 0 -evalue 1E-4 -subject_besthit -outfmt '6 qseqid qlen sacc salltitles staxids pident length evalue'
}

#tool to extract contigs from assembly Blast to fasta
function blastToFasta {
    grep -i ".*" "$outpath"/"$library_id"_"$nt_db_basename"_nt_blastn_results.txt | cut -f1 | uniq > "$outpath"/"$library_id""_temp_contig_names.txt"
    grep -A1 -I -Ff "$outpath"/"$library_id""_temp_contig_names.txt" $input > "$outpath"/"$library_id"_"$nt_db_basename"_nt_blastcontigs.fasta
    sed -i 's/--//' "$outpath"/"$library_id"_"$nt_db_basename"_nt_blastcontigs.fasta
    sed -i '/^[[:space:]]*$/d' "$outpath"/"$library_id"_"$nt_db_basename"_nt_blastcontigs.fasta
    sed --posix -i "/^\>/ s/$/"_$library_id"/" "$outpath"/"$library_id"_"$nt_db_basename"_nt_blastcontigs.fasta
    rm "$outpath"/"$library_id""_temp_contig_names.txt"
}

# Setting variables - you shouldn't really need to change these other than resource allocations
library_id="$(basename -- "$input")"
outpath="$wd"
CPU=6

cd "$wd" || exit

Blastn
blastToFasta
