#!/bin/bash
###############################################################################################################
#                                            BatchArtemisSRAMiner                                             #   
#                                                JCO Mifsud                                                   # 
#                                                   2023                                                      # 
###############################################################################################################

#PBS -P RDS-FSC-VELAB-RW
#PBS -N fastqc
#PBS -l select=1:ncpus=12:mem=120GB
#PBS -l walltime=48:00:00
#PBS -M jmif9945@uni.sydney.edu.au
#PBS -m abe

module load fastqc/0.11.8
cd /project/"$root_project"/"$project"/fastqc || exit

readarray -t myarray < "$file_of_accessions"
export library_run=${myarray["$PBS_ARRAY_INDEX"]}

fastqc "$library_run" \
    --format fastq \
    --threads 12 \
    --outdir /project/"$root_project"/"$project"/fastqc

